DROP USER JPA3 CASCADE;
CREATE USER JPA3 IDENTIFIED BY JPA3;
GRANT CONNECT, RESOURCE TO JPA3;

CONNECT JPA3/JPA3

DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PRODUTO;

CREATE SEQUENCE SEQ_PRODUTO;

CREATE TABLE PRODUTO
(ID             NUMBER(5)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30) 
   CONSTRAINT PRODUTO_NOME_NN
   NOT NULL,
 LANCE_MINIMO  NUMBER(8,2)
   CONSTRAINT PRODUTO_LANCE_MINIMO_NN
   NOT NULL,
 DATA_CADASTRO  DATE
   CONSTRAINT PRODUTO_DATA_CADASTRO_NN
   NOT NULL,
 DATA_VENDA     DATE,
 VERSAO         NUMBER(9));

INSERT INTO PRODUTO(ID, NOME, LANCE_MINIMO, DATA_CADASTRO, VERSAO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 20 POL', 2000, SYSDATE, 0);

INSERT INTO PRODUTO(ID, NOME, LANCE_MINIMO, DATA_CADASTRO, VERSAO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 22 POL', 2500, SYSDATE, 0);

COMMIT;
